"""Namespace reference maps for findings tags.— CWE, MITRE ATT&CK, OWASP, CAPEC, D3FEND."""

CWE = {
    "cwe:20": "Improper Input Validation",
    "cwe:22": "Path Traversal",
    "cwe:77": "Command Injection",
    "cwe:78": "OS Command Injection",
    "cwe:79": "Cross-Site Scripting (XSS)",
    "cwe:89": "SQL Injection",
    "cwe:90": "LDAP Injection",
    "cwe:91": "XML Injection",
    "cwe:94": "Code Injection",
    "cwe:95": "Eval Injection",
    "cwe:99": "Resource Injection",
    "cwe:116": "Improper Encoding/Escaping",
    "cwe:118": "Buffer Overflow",
    "cwe:119": "Buffer Over-read/Over-write",
    "cwe:120": "Classic Buffer Overflow",
    "cwe:121": "Stack-based Buffer Overflow",
    "cwe:122": "Heap-based Buffer Overflow",
    "cwe:125": "Out-of-bounds Read",
    "cwe:134": "Format String",
    "cwe:190": "Integer Overflow",
    "cwe:200": "Information Exposure",
    "cwe:201": "Information Exposure Through Sent Data",
    "cwe:250": "Execution with Unnecessary Privileges",
    "cwe:255": "Credentials Management",
    "cwe:256": "Plaintext Storage of Password",
    "cwe:257": "Storing Passwords in Recoverable Format",
    "cwe:259": "Hard-coded Password",
    "cwe:261": "Weak Cryptography for Passwords",
    "cwe:264": "Permissions, Privileges, ACLs",
    "cwe:269": "Improper Privilege Management",
    "cwe:276": "Incorrect Default Permissions",
    "cwe:281": "Improper Permission Preservation",
    "cwe:285": "Improper Authorization",
    "cwe:287": "Authentication Bypass",
    "cwe:290": "Authentication Bypass by Spoofing",
    "cwe:295": "Improper Certificate Validation",
    "cwe:297": "Improper Hostname Verification",
    "cwe:300": "Man-in-the-Middle",
    "cwe:302": "Authentication Bypass by Assumed-Immutable Data",
    "cwe:306": "Missing Authentication",
    "cwe:307": "Brute Force",
    "cwe:311": "Missing Encryption",
    "cwe:312": "Cleartext Storage of Sensitive Data",
    "cwe:319": "Cleartext Transmission",
    "cwe:321": "Hard-coded Cryptographic Key",
    "cwe:322": "Key Exchange without Entity Auth",
    "cwe:326": "Inadequate Encryption Strength",
    "cwe:327": "Broken/Risky Crypto Algorithm",
    "cwe:328": "Weak Hash",
    "cwe:330": "Insufficiently Random Values",
    "cwe:345": "Insufficient Data Integrity Verification",
    "cwe:346": "Origin Validation Error (CORS)",
    "cwe:347": "Improper Signature Verification",
    "cwe:352": "Cross-Site Request Forgery (CSRF)",
    "cwe:362": "Race Condition",
    "cwe:367": "TOCTOU Race Condition",
    "cwe:377": "Insecure Temporary File",
    "cwe:378": "Insecure Temp File (Credentials)",
    "cwe:379": "Insecure Temp File (Sensitive Data)",
    "cwe:384": "Session Fixation",
    "cwe:400": "Uncontrolled Resource Consumption",
    "cwe:401": "Missing Release of Memory",
    "cwe:402": "Transmission of Private Resources",
    "cwe:404": "Improper Resource Shutdown",
    "cwe:415": "Double Free",
    "cwe:416": "Use-After-Free",
    "cwe:425": "Direct Request (Forced Browsing)",
    "cwe:426": "Untrusted Search Path",
    "cwe:434": "Unrestricted File Upload",
    "cwe:435": "Improper Interaction Between Correct Behaviors",
    "cwe:441": "Unintended Proxy/Intermediary",
    "cwe:444": "HTTP Request Smuggling",
    "cwe:451": "User Interface Misrepresentation",
    "cwe:470": "Use of External-Controlled Input to Select Classes",
    "cwe:471": "Modification of Assumed-Immutable Data",
    "cwe:476": "NULL Pointer Dereference",
    "cwe:489": "Debug Left In",
    "cwe:494": "Download of Code Without Integrity Check",
    "cwe:501": "Trust Boundary Violation",
    "cwe:502": "Deserialization of Untrusted Data",
    "cwe:506": "Embedded Malicious Code",
    "cwe:508": "Reusable Password Recovery",
    "cwe:521": "Weak Password Requirements",
    "cwe:522": "Insufficiently Protected Credentials",
    "cwe:523": "Unprotected Transport of Credentials",
    "cwe:525": "Web Browser Cache Containing Sensitive Data",
    "cwe:532": "Information Exposure Through Log Files",
    "cwe:539": "Persistent Cookies Containing Sensitive Data",
    "cwe:540": "Information Exposure Through Source Code",
    "cwe:548": "Directory Listing",
    "cwe:549": "Missing Password Field Masking",
    "cwe:552": "Files/Directories Accessible to External Parties",
    "cwe:565": "Cookie/Session Poisoning",
    "cwe:598": "Information Exposure Through Query Strings",
    "cwe:601": "URL Redirection to Untrusted Site (Open Redirect)",
    "cwe:602": "Client-Side Enforcement of Server-Side Security",
    "cwe:603": "Use of Client-Side Authentication",
    "cwe:610": "Externally Controlled Reference to a Resource",
    "cwe:611": "Improper XML Parsing (XXE)",
    "cwe:613": "Insufficient Session Expiration",
    "cwe:614": "Sensitive Cookie Without Secure/HttpOnly",
    "cwe:620": "Unverified Password Change",
    "cwe:639": "Insecure Direct Object Reference (IDOR)",
    "cwe:640": "Weak Password Recovery",
    "cwe:641": "Information Exposure Through Error Messages",
    "cwe:642": "External Control of Critical State Data",
    "cwe:643": "XPath Injection",
    "cwe:646": "Reliance on File Name or Extension",
    "cwe:647": "Use of Non-Canonical URL Paths",
    "cwe:648": "Incorrect Use of Privileged APIs",
    "cwe:649": "Reliance on Obfuscation",
    "cwe:652": "XQuery Injection",
    "cwe:657": "Violation of Secure Design Principles",
    "cwe:662": "Improper Synchronization",
    "cwe:663": "Use of Non-Cryptographic PRNG",
    "cwe:664": "Improper Control of a Resource Through its Lifetime",
    "cwe:665": "Improper Initialization",
    "cwe:667": "Improper Locking",
    "cwe:668": "Exposure of Resource to Wrong Sphere",
    "cwe:669": "Incorrect Resource Transfer",
    "cwe:670": "Always-Incorrect Control Flow Implementation",
    "cwe:672": "Operation on Resource After Expiration",
    "cwe:674": "Uncontrolled Recursion",
    "cwe:676": "Use of Potentially Dangerous Function",
    "cwe:680": "Integer Overflow to Buffer Overflow",
    "cwe:681": "Incorrect Type Conversion",
    "cwe:682": "Incorrect Calculation",
    "cwe:693": "Protection Mechanism Failure",
    "cwe:694": "Use of Multiple Resources with Duplicate Identifier",
    "cwe:697": "Insufficient Comparison",
    "cwe:703": "Improper Exception Handling",
    "cwe:704": "Incorrect Type Cast",
    "cwe:706": "Use of Incorrectly-Resolved Reference",
    "cwe:707": "Improper Enforcement of Message Integrity",
    "cwe:708": "Incorrect Ownership Assignment",
    "cwe:710": "Adherence to Coding Standards",
    "cwe:712": "Improper Security Configuration",
    "cwe:713": "Omitted Security-relevant Information",
    "cwe:715": "Improper Security Control",
    "cwe:716": "Incorrect Security Configuration",
    "cwe:720": "OWASP Top 10 2021 Category mapping",
    "cwe:732": "Incorrect Permission Assignment",
    "cwe:749": "Exposed Dangerous Method",
    "cwe:754": "Improper Check for Unusual Conditions",
    "cwe:759": "Use of One-Way Hash without Salt",
    "cwe:760": "Use of One-Way Hash with Predictable Salt",
    "cwe:762": "Mismatched Memory Management",
    "cwe:763": "Release of Invalid Pointer",
    "cwe:770": "Allocation of Resources Without Limits",
    "cwe:772": "Missing Release of Resource",
    "cwe:776": "XML Entity Expansion (Billion Laughs)",
    "cwe:777": "Regular Expression without Anchors",
    "cwe:778": "Insufficient Logging",
    "cwe:779": "Logging of Sensitive Data",
    "cwe:782": "Exposed IOCTL",
    "cwe:784": "Reliance on Cookies without Integrity",
    "cwe:787": "Out-of-bounds Write",
    "cwe:788": "Access of Memory Location After End of Buffer",
    "cwe:789": "Memory Allocation with Excessive Size",
    "cwe:798": "Use of Hard-coded Credentials",
    "cwe:799": "Improper Control of Interaction Frequency",
    "cwe:804": "Guessable CAPTCHA",
    "cwe:807": "Reliance on Untrusted Inputs",
    "cwe:822": "Untrusted Pointer Dereference",
    "cwe:823": "Use of Out-of-range Pointer Offset",
    "cwe:824": "Access of Uninitialized Pointer",
    "cwe:825": "Expired Pointer Dereference",
    "cwe:826": "Premature Release of Resource",
    "cwe:827": "Improper Control of Document Type",
    "cwe:828": "Signal Handler with Non-reentrant Function",
    "cwe:829": "Inclusion from Untrusted Source",
    "cwe:830": "Inclusion of Web Functionality from Untrusted Source",
    "cwe:831": "Signal Handler Function Override",
    "cwe:832": "Unlock of Resource Not Locked",
    "cwe:833": "Deadlock",
    "cwe:834": "Excessive Iteration",
    "cwe:835": "Infinite Loop",
    "cwe:836": "Use of Password Hash Instead of Password",
    "cwe:837": "Improper Enforcement of Intent",
    "cwe:838": "Inappropriate Encoding for Output Context",
    "cwe:839": "Numeric Range Comparison",
    "cwe:840": "Business Logic Errors",
    "cwe:841": "Improper Enforcement of Workflow",
    "cwe:842": "Placement of User into Incorrect Group",
    "cwe:843": "Type Confusion",
    "cwe:844": "Unsafe Reflection",
    "cwe:845": "The J2EE Bad Practices",
    "cwe:846": "Unsafe Mobile Code",
    "cwe:847": "Insufficient Encapsulation",
    "cwe:848": "Certification - Other Validation Errors",
    "cwe:849": "Certification - Data Protection",
    "cwe:850": "Certification - Cryptographic Failures",
    "cwe:851": "Certification - Access Control",
    "cwe:852": "Certification - Identification & Authentication",
    "cwe:853": "Certification - System & Communications Protection",
    "cwe:854": "Certification - System & Information Integrity",
    "cwe:855": "Certification - Configuration Management",
    "cwe:856": "Certification - Software/Firmware Integrity",
    "cwe:857": "Certification - Information Flow",
    "cwe:858": "Certification - Auditing & Accountability",
    "cwe:859": "Certification - Maintenance",
    "cwe:860": "Certification - Media Protection",
    "cwe:861": "Certification - Personnel Security",
    "cwe:862": "Missing Authorization",
    "cwe:863": "Incorrect Authorization",
    "cwe:864": "Signature Forgery",
    "cwe:865": "Improper Enforcement of Singleton",
    "cwe:866": "Race Condition for Shared Resource",
    "cwe:867": "Improper Initialization of a Shared Resource",
    "cwe:868": "Race Condition for Write to Shared Resource",
    "cwe:869": "Race Condition for Read of Shared Resource",
    "cwe:870": "Improper API Usage",
    "cwe:871": "Improper API Implementation",
    "cwe:872": "Alternate Channel",
    "cwe:873": "Improper API Authorization",
    "cwe:874": "Improper API Documentation",
    "cwe:875": "Improper API Versioning",
    "cwe:876": "Improper API Encryption",
    "cwe:877": "Improper API Logging",
    "cwe:878": "Improper API Input Validation",
    "cwe:879": "Improper API Output Encoding",
    "cwe:880": "Improper API Session Management",
    "cwe:881": "Improper API Error Handling",
    "cwe:882": "Improper API Rate Limiting",
    "cwe:883": "Improper API Caching",
    "cwe:884": "Improper API CORS Configuration",
    "cwe:885": "Improper API Content-Type Handling",
    "cwe:886": "Improper API Header Validation",
    "cwe:887": "Improper API Authentication",
}

_OWASP_WEB = {
    "owasp-web:A01:2021": "Broken Access Control",
    "owasp-web:A02:2021": "Cryptographic Failures",
    "owasp-web:A03:2021": "Injection",
    "owasp-web:A04:2021": "Insecure Design",
    "owasp-web:A05:2021": "Security Misconfiguration",
    "owasp-web:A06:2021": "Vulnerable and Outdated Components",
    "owasp-web:A07:2021": "Identification and Authentication Failures",
    "owasp-web:A08:2021": "Software and Data Integrity Failures",
    "owasp-web:A09:2021": "Security Logging and Monitoring Failures",
    "owasp-web:A10:2021": "Server-Side Request Forgery (SSRF)",
}
OWASP_WEB = {k: (v, "web") for k, v in _OWASP_WEB.items()}

_OWASP_AI = {
    "owasp-ai:AIL1-01": "Input Manipulation (Prompt Injection)",
    "owasp-ai:AIL1-02": "Model Poisoning",
    "owasp-ai:AIL1-03": "Data Poisoning",
    "owasp-ai:AIL1-04": "Supply Chain Vulnerabilities",
    "owasp-ai:AIL1-05": "Sensitive Information Disclosure",
    "owasp-ai:AIL1-06": "Insecure Output Handling",
    "owasp-ai:AIL1-07": "Model Theft",
    "owasp-ai:AIL1-08": "Denial of Service (DoS)",
    "owasp-ai:AIL1-09": "Insecure Integration",
    "owasp-ai:AIL1-10": "Improper Access Control",
    "owasp-ai:AIL2-01": "Adversarial Perturbations",
    "owasp-ai:AIL2-02": "Gradient Leakage",
    "owasp-ai:AIL2-03": "Model Inversion",
    "owasp-ai:AIL2-04": "Membership Inference",
    "owasp-ai:AIL2-05": "Model Extraction",
    "owasp-ai:AIL2-06": "Attribute Inference",
    "owasp-ai:AIL2-07": "Data Reconstruction",
    "owasp-ai:AIL2-08": "Label Flipping",
    "owasp-ai:AIL2-09": "Backdoor Attacks",
    "owasp-ai:AIL2-10": "Evasion Attacks",
    "owasp-ai:AIL3-01": "Excessive Agency",
    "owasp-ai:AIL3-02": "Unsafe Reflection",
    "owasp-ai:AIL3-03": "Tool Misuse",
    "owasp-ai:AIL3-04": "Permissive Delegation",
    "owasp-ai:AIL3-05": "Unbounded Resource Consumption",
    "owasp-ai:AIL3-06": "Lack of Human in the Loop",
    "owasp-ai:AIL3-07": "Improper Sandboxing",
    "owasp-ai:AIL3-08": "Insufficient Monitoring",
    "owasp-ai:AIL3-09": "Unvalidated Output Consumption",
    "owasp-ai:AIL3-10": "Insufficient Audit Trail",
}
OWASP_AI = {k: (v, "ai") for k, v in _OWASP_AI.items()}

_MITRE_ATTACK = {
    "mitre-attack:T1003": "OS Credential Dumping",
    "mitre-attack:T1003.001": "OS Credential Dumping: LSASS Memory",
    "mitre-attack:T1003.002": "OS Credential Dumping: SAM/Security Hive",
    "mitre-attack:T1003.003": "OS Credential Dumping: NTDS",
    "mitre-attack:T1003.004": "OS Credential Dumping: LSA Secrets",
    "mitre-attack:T1003.005": "OS Credential Dumping: Cached Domain Credentials",
    "mitre-attack:T1003.006": "OS Credential Dumping: DCSync",
    "mitre-attack:T1003.007": "OS Credential Dumping: Proc Filesystem",
    "mitre-attack:T1005": "Data from Local System",
    "mitre-attack:T1007": "System Service Discovery",
    "mitre-attack:T1010": "Application Window Discovery",
    "mitre-attack:T1012": "Query Registry",
    "mitre-attack:T1016": "System Network Configuration Discovery",
    "mitre-attack:T1018": "Remote System Discovery",
    "mitre-attack:T1020": "Automated Exfiltration",
    "mitre-attack:T1021": "Remote Services",
    "mitre-attack:T1021.001": "Remote Services: Remote Desktop Protocol",
    "mitre-attack:T1021.002": "Remote Services: SMB/WMI",
    "mitre-attack:T1021.003": "Remote Services: Distributed COM",
    "mitre-attack:T1021.004": "Remote Services: SSH",
    "mitre-attack:T1021.005": "Remote Services: VNC",
    "mitre-attack:T1021.006": "Remote Services: Windows Remote Management",
    "mitre-attack:T1021.007": "Remote Services: RPC",
    "mitre-attack:T1027": "Obfuscated Files or Information",
    "mitre-attack:T1027.001": "Obfuscation: Binary Padding",
    "mitre-attack:T1027.002": "Obfuscation: Software Packing",
    "mitre-attack:T1027.003": "Obfuscation: Steganography",
    "mitre-attack:T1027.004": "Obfuscation: Compile After Delivery",
    "mitre-attack:T1027.005": "Obfuscation: Encrypted/Encoded File",
    "mitre-attack:T1027.006": "Obfuscation: HTML Smuggling",
    "mitre-attack:T1027.007": "Obfuscation: Dynamic API Resolution",
    "mitre-attack:T1027.008": "Obfuscation: Stripped Binaries",
    "mitre-attack:T1027.009": "Obfuscation: Embedded Payloads",
    "mitre-attack:T1027.010": "Obfuscation: Command Obfuscation",
    "mitre-attack:T1027.011": "Obfuscation: Fileless Storage",
    "mitre-attack:T1027.012": "Obfuscation: LNK Icon Smuggling",
    "mitre-attack:T1027.013": "Obfuscation: Encrypted Channel",
    "mitre-attack:T1027.014": "Obfuscation: Polymorphic Code",
    "mitre-attack:T1030": "Data Transfer Size Limits",
    "mitre-attack:T1036": "Masquerading",
    "mitre-attack:T1036.001": "Masquerading: Invalid Code Signature",
    "mitre-attack:T1036.002": "Masquerading: Right-to-Left Override",
    "mitre-attack:T1036.003": "Masquerading: Rename System Utilities",
    "mitre-attack:T1036.004": "Masquerading: Masquerade Task or Service",
    "mitre-attack:T1036.005": "Masquerading: Match Legitimate Name",
    "mitre-attack:T1036.006": "Masquerading: Space After Filename",
    "mitre-attack:T1036.007": "Masquerading: Double File Extension",
    "mitre-attack:T1037": "Boot or Logon Initialization Scripts",
    "mitre-attack:T1037.001": "Logon Script (Windows)",
    "mitre-attack:T1037.002": "Login Hook (Mac)",
    "mitre-attack:T1037.003": "Network Logon Script",
    "mitre-attack:T1037.004": "RC Scripts (Unix)",
    "mitre-attack:T1037.005": "Startup Items",
    "mitre-attack:T1039": "Data from Network Shared Drive",
    "mitre-attack:T1040": "Network Sniffing",
    "mitre-attack:T1041": "Exfiltration Over C2 Channel",
    "mitre-attack:T1046": "Network Service Discovery",
    "mitre-attack:T1047": "Windows Management Instrumentation",
    "mitre-attack:T1048": "Exfiltration Over Alternative Protocol",
    "mitre-attack:T1049": "System Network Connections Discovery",
    "mitre-attack:T1050": "New Service",
    "mitre-attack:T1052": "Exfiltration Over Physical Medium",
    "mitre-attack:T1053.002": "Scheduled Task (At)",
    "mitre-attack:T1053.005": "Scheduled Task (Scheduled Task)",
    "mitre-attack:T1053.006": "Scheduled Task (Systemd Timers)",
    "mitre-attack:T1055": "Process Injection",
    "mitre-attack:T1055.001": "Process Injection: Dynamic-link Library Injection",
    "mitre-attack:T1055.002": "Process Injection: Portable Executable Injection",
    "mitre-attack:T1055.003": "Process Injection: Thread Execution Hijacking",
    "mitre-attack:T1055.004": "Process Injection: Asynchronous Procedure Call",
    "mitre-attack:T1055.005": "Process Injection: Thread Local Storage",
    "mitre-attack:T1055.008": "Process Injection: Nt Map View Of Section",
    "mitre-attack:T1055.009": "Process Injection: Proc Memory",
    "mitre-attack:T1055.011": "Process Injection: Extra Window Memory Injection",
    "mitre-attack:T1055.012": "Process Injection: Process Hollowing",
    "mitre-attack:T1055.013": "Process Injection: Process Doppelgänging",
    "mitre-attack:T1055.014": "Process Injection: VDSO Hijacking",
    "mitre-attack:T1056": "Input Capture",
    "mitre-attack:T1056.001": "Input Capture: Keylogging",
    "mitre-attack:T1056.002": "Input Capture: GUI Input Capture",
    "mitre-attack:T1056.003": "Input Capture: Web Portal Capture",
    "mitre-attack:T1056.004": "Input Capture: Credential API Hooking",
    "mitre-attack:T1056.005": "Input Capture: Mailbox Capture",
    "mitre-attack:T1057": "Process Discovery",
    "mitre-attack:T1059": "Command and Scripting Interpreter",
    "mitre-attack:T1059.001": "Command Interpreter: PowerShell",
    "mitre-attack:T1059.002": "Command Interpreter: AppleScript",
    "mitre-attack:T1059.003": "Command Interpreter: Windows Command Shell",
    "mitre-attack:T1059.004": "Command Interpreter: Unix Shell",
    "mitre-attack:T1059.005": "Command Interpreter: Visual Basic",
    "mitre-attack:T1059.006": "Command Interpreter: Python",
    "mitre-attack:T1059.007": "Command Interpreter: JavaScript",
    "mitre-attack:T1059.008": "Command Interpreter: Network Device CLI",
    "mitre-attack:T1059.009": "Command Interpreter: Cloud API",
    "mitre-attack:T1059.010": "Command Interpreter: AutoHotKey/AutoIt",
    "mitre-attack:T1068": "Exploitation for Privilege Escalation",
    "mitre-attack:T1069": "Permission Groups Discovery",
    "mitre-attack:T1069.001": "Local Groups",
    "mitre-attack:T1069.002": "Domain Groups",
    "mitre-attack:T1069.003": "Cloud Groups",
    "mitre-attack:T1070": "Indicator Removal",
    "mitre-attack:T1070.001": "Indicator Removal: Clear Event Logs",
    "mitre-attack:T1070.002": "Indicator Removal: Clear Linux/Mac Logs",
    "mitre-attack:T1070.003": "Indicator Removal: Clear Command History",
    "mitre-attack:T1070.004": "Indicator Removal: File Deletion",
    "mitre-attack:T1070.005": "Indicator Removal: Network Share Connection Removal",
    "mitre-attack:T1070.006": "Indicator Removal: Timestomp",
    "mitre-attack:T1070.007": "Indicator Removal: Clear Windows Logs",
    "mitre-attack:T1070.008": "Indicator Removal: Clear Mailbox Data",
    "mitre-attack:T1070.009": "Indicator Removal: Clear Persistence",
    "mitre-attack:T1071": "Application Layer Protocol",
    "mitre-attack:T1071.001": "Web Protocols",
    "mitre-attack:T1071.002": "File Transfer Protocols",
    "mitre-attack:T1071.003": "Mail Protocols",
    "mitre-attack:T1071.004": "DNS",
    "mitre-attack:T1071.005": "Custom Protocols",
    "mitre-attack:T1072": "Software Deployment Tools",
    "mitre-attack:T1074": "Data Staged",
    "mitre-attack:T1074.001": "Local Data Staging",
    "mitre-attack:T1074.002": "Remote Data Staging",
    "mitre-attack:T1075": "Pass-the-Hash",
    "mitre-attack:T1076": "Remote Desktop Protocol",
    "mitre-attack:T1078": "Valid Accounts",
    "mitre-attack:T1078.001": "Default Accounts",
    "mitre-attack:T1078.002": "Domain Accounts",
    "mitre-attack:T1078.003": "Local Accounts",
    "mitre-attack:T1078.004": "Cloud Accounts",
    "mitre-attack:T1082": "System Information Discovery",
    "mitre-attack:T1083": "File and Directory Discovery",
    "mitre-attack:T1087": "Account Discovery",
    "mitre-attack:T1087.001": "Local Account",
    "mitre-attack:T1087.002": "Domain Account",
    "mitre-attack:T1087.003": "Email Account",
    "mitre-attack:T1087.004": "Cloud Account",
    "mitre-attack:T1090": "Proxy",
    "mitre-attack:T1090.001": "Internal Proxy",
    "mitre-attack:T1090.002": "External Proxy",
    "mitre-attack:T1090.003": "Multi-hop Proxy",
    "mitre-attack:T1090.004": "Domain Fronting",
    "mitre-attack:T1091": "Replication Through Removable Media",
    "mitre-attack:T1095": "Non-Application Layer Protocol",
    "mitre-attack:T1098": "Account Manipulation",
    "mitre-attack:T1098.001": "Additional Credentials",
    "mitre-attack:T1098.002": "Additional Email Delegate Permissions",
    "mitre-attack:T1098.003": "Additional Cloud Roles",
    "mitre-attack:T1098.004": "SSH Authorized Keys",
    "mitre-attack:T1098.005": "Device Registration",
    "mitre-attack:T1102": "Web Service",
    "mitre-attack:T1102.001": "Dead Drop Resolver",
    "mitre-attack:T1102.002": "Bidirectional Communication",
    "mitre-attack:T1102.003": "One-Way Communication",
    "mitre-attack:T1104": "Multi-Stage Channels",
    "mitre-attack:T1105": "Ingress Tool Transfer",
    "mitre-attack:T1106": "Native API",
    "mitre-attack:T1110": "Brute Force",
    "mitre-attack:T1110.001": "Password Guessing",
    "mitre-attack:T1110.002": "Password Cracking",
    "mitre-attack:T1110.003": "Password Spraying",
    "mitre-attack:T1110.004": "Credential Stuffing",
    "mitre-attack:T1111": "Two-Factor Authentication Interception",
    "mitre-attack:T1112": "Modify Registry",
    "mitre-attack:T1113": "Screen Capture",
    "mitre-attack:T1114": "Email Collection",
    "mitre-attack:T1114.001": "Local Email Collection",
    "mitre-attack:T1114.002": "Remote Email Collection",
    "mitre-attack:T1114.003": "Email Forwarding Rule",
    "mitre-attack:T1115": "Clipboard Data",
    "mitre-attack:T1119": "Automated Collection",
    "mitre-attack:T1120": "Peripheral Device Discovery",
    "mitre-attack:T1123": "Audio Capture",
    "mitre-attack:T1124": "System Time Discovery",
    "mitre-attack:T1125": "Video Capture",
    "mitre-attack:T1127": "Trusted Developer Utilities",
    "mitre-attack:T1127.001": "MSBuild",
    "mitre-attack:T1127.002": "DNX",
    "mitre-attack:T1129": "Shared Modules",
    "mitre-attack:T1132": "Data Encoding",
    "mitre-attack:T1132.001": "Standard Encoding",
    "mitre-attack:T1132.002": "Non-Standard Encoding",
    "mitre-attack:T1134": "Access Token Manipulation",
    "mitre-attack:T1134.001": "Token Impersonation/Theft",
    "mitre-attack:T1134.002": "Create Process with Token",
    "mitre-attack:T1134.003": "Make and Impersonate Token",
    "mitre-attack:T1134.004": "Parent PID Spoofing",
    "mitre-attack:T1134.005": "SID-History Injection",
    "mitre-attack:T1134.006": "Kerberos Token Manipulation",
    "mitre-attack:T1135": "Network Share Discovery",
    "mitre-attack:T1136": "Create Account",
    "mitre-attack:T1136.001": "Local Account",
    "mitre-attack:T1136.002": "Domain Account",
    "mitre-attack:T1136.003": "Cloud Account",
    "mitre-attack:T1137": "Office Application Startup",
    "mitre-attack:T1137.001": "Office Template Macros",
    "mitre-attack:T1137.002": "Office Add-ins",
    "mitre-attack:T1137.003": "Outlook Rules",
    "mitre-attack:T1137.004": "Outlook Home Page",
    "mitre-attack:T1137.005": "Outlook Forms",
    "mitre-attack:T1137.006": "Office Test",
    "mitre-attack:T1140": "Deobfuscate/Decode Files or Information",
    "mitre-attack:T1141": "Input Capture: Windows GUI",
    "mitre-attack:T1142": "Input Capture: Windows Credential UI",
    "mitre-attack:T1143": "Input Capture: Windows Password Filter",
    "mitre-attack:T1145": "Private Keys",
    "mitre-attack:T1146": "Clear Command History",
    "mitre-attack:T1147": "Hidden Window",
    "mitre-attack:T1148": "HISTCONTROL",
    "mitre-attack:T1149": "Organizational Information/Environment Discovery",
    "mitre-attack:T1150": "Securityd Memory",
    "mitre-attack:T1151": "Space after Filename",
    "mitre-attack:T1152": "Launchctl",
    "mitre-attack:T1153": "Source",
    "mitre-attack:T1154": "Trap",
    "mitre-attack:T1155": "AppleScript",
    "mitre-attack:T1156": ".bash_profile and .bashrc",
    "mitre-attack:T1157": "Dylib Hijacking",
    "mitre-attack:T1158": "Hidden Files and Directories",
    "mitre-attack:T1159": "Launch Agent",
    "mitre-attack:T1160": "Launch Daemon",
    "mitre-attack:T1161": "LC_LOAD_DYLIB Addition",
    "mitre-attack:T1162": "Login Item",
    "mitre-attack:T1163": "Rc.common",
    "mitre-attack:T1164": "Re-opened Applications",
    "mitre-attack:T1165": "Startup Item",
    "mitre-attack:T1166": "Setuid and Setgid",
    "mitre-attack:T1167": "Security.framework",
    "mitre-attack:T1168": "Local Job Scheduling",
    "mitre-attack:T1169": "Sudo",
    "mitre-attack:T1170": "MSHTA",
    "mitre-attack:T1171": "LLMNR/NBT-NS Poisoning and Relay",
    "mitre-attack:T1172": "Hooking",
    "mitre-attack:T1173": "DLL Side-Loading",
    "mitre-attack:T1174": "Password Filter DLL",
    "mitre-attack:T1175": "Distributed Component Object Model (DCOM)",
    "mitre-attack:T1176": "Browser Extensions",
    "mitre-attack:T1177": "LSASS Driver",
    "mitre-attack:T1178": "SID-History Injection",
    "mitre-attack:T1179": "Hooking: Windows Hooks",
    "mitre-attack:T1180": "Screensaver",
    "mitre-attack:T1181": "Extra Window Memory Injection",
    "mitre-attack:T1182": "AppCert DLLs",
    "mitre-attack:T1183": "Image File Execution Options Injection",
    "mitre-attack:T1184": "SSH Hijacking",
    "mitre-attack:T1185": "Browser Session Hijacking",
    "mitre-attack:T1186": "Process Doppelgänging",
    "mitre-attack:T1187": "Forced Authentication",
    "mitre-attack:T1188": "Multi-hop Proxy",
    "mitre-attack:T1189": "Drive-by Compromise",
    "mitre-attack:T1190": "Exploit Public-Facing Application",
    "mitre-attack:T1191": "CMSTP",
    "mitre-attack:T1192": "Spearphishing Link",
    "mitre-attack:T1193": "Spearphishing Attachment",
    "mitre-attack:T1194": "Spearphishing via Service",
    "mitre-attack:T1195": "Supply Chain Compromise",
    "mitre-attack:T1195.001": "Compromise Software Dependencies",
    "mitre-attack:T1195.002": "Compromise Software/SDK",
    "mitre-attack:T1195.003": "Compromise Hardware",
    "mitre-attack:T1196": "Control Panel Items",
    "mitre-attack:T1197": "BITS Jobs",
    "mitre-attack:T1198": "SIP and Trust Provider Hijacking",
    "mitre-attack:T1199": "Trusted Relationship",
    "mitre-attack:T1200": "Hardware Additions",
    "mitre-attack:T1201": "Password Policy Discovery",
    "mitre-attack:T1202": "Indirect Command Execution",
    "mitre-attack:T1203": "Exploitation for Client Execution",
    "mitre-attack:T1204": "User Execution",
    "mitre-attack:T1204.001": "Malicious Link",
    "mitre-attack:T1204.002": "Malicious File",
    "mitre-attack:T1204.003": "Malicious Image",
    "mitre-attack:T1205": "Port Knocking",
    "mitre-attack:T1205.001": "Port Knocking",
    "mitre-attack:T1205.002": "Port Knocking",
    "mitre-attack:T1206": "SigRed",
    "mitre-attack:T1207": "Rogue Domain Controller",
    "mitre-attack:T1208": "Kerberoasting",
    "mitre-attack:T1209": "AS-REP Roasting",
    "mitre-attack:T1210": "Exploitation of Remote Services",
    "mitre-attack:T1211": "Exploitation for Defense Evasion",
    "mitre-attack:T1212": "Exploitation for Credential Access",
    "mitre-attack:T1213": "Data from Information Repositories",
    "mitre-attack:T1213.001": "Code Repositories",
    "mitre-attack:T1213.002": "SharePoint",
    "mitre-attack:T1213.003": "Confluence",
    "mitre-attack:T1214": "Credentials in Registry",
    "mitre-attack:T1215": "Kernel Modules and Extensions",
    "mitre-attack:T1216": "Signed Scripts",
    "mitre-attack:T1216.001": "PubPrn",
    "mitre-attack:T1217": "Browser Bookmark Discovery",
    "mitre-attack:T1218": "Signed Binary Proxy Execution",
    "mitre-attack:T1218.001": "Msiexec",
    "mitre-attack:T1218.002": "Mshta",
    "mitre-attack:T1218.003": "Cmstp",
    "mitre-attack:T1218.004": "InstallUtil",
    "mitre-attack:T1218.005": "Mshta",
    "mitre-attack:T1218.007": "Msiexec",
    "mitre-attack:T1218.008": "Regsvcs/Regasm",
    "mitre-attack:T1218.009": "Regsvr32",
    "mitre-attack:T1218.010": "Regsvr32: Regsvr32.exe",
    "mitre-attack:T1218.011": "Rundll32",
    "mitre-attack:T1218.012": "Verclsid",
    "mitre-attack:T1218.013": "Mavinject",
    "mitre-attack:T1219": "Remote Access Software",
    "mitre-attack:T1220": "XSL Script Processing",
    "mitre-attack:T1221": "Template Injection",
    "mitre-attack:T1222": "File Permissions Modification",
    "mitre-attack:T1222.001": "Windows File/Dir Permissions",
    "mitre-attack:T1222.002": "Linux/Mac File/Dir Permissions",
    "mitre-attack:T1223": "Scheduled Task/Job",
    "mitre-attack:T1224": "Kerberos Ticket Manipulation",
    "mitre-attack:T1482": "Domain Trust Discovery",
    "mitre-attack:T1484": "Domain Policy Modification",
    "mitre-attack:T1484.001": "Group Policy Modification",
    "mitre-attack:T1484.002": "Trust Modification",
    "mitre-attack:T1485": "Data Destruction",
    "mitre-attack:T1486": "Data Encrypted for Impact",
    "mitre-attack:T1487": "Disk Wipe",
    "mitre-attack:T1488": "Disk Content Wipe",
    "mitre-attack:T1489": "Service Stop",
    "mitre-attack:T1490": "Inhibit System Recovery",
    "mitre-attack:T1491": "Defacement",
    "mitre-attack:T1491.001": "Internal Defacement",
    "mitre-attack:T1491.002": "External Defacement",
    "mitre-attack:T1492": "Stored Data Manipulation",
    "mitre-attack:T1493": "Transmitted Data Manipulation",
    "mitre-attack:T1494": "Runtime Data Manipulation",
    "mitre-attack:T1495": "Firmware Corruption",
    "mitre-attack:T1496": "Resource Hijacking",
    "mitre-attack:T1497": "Virtualization/Sandbox Evasion",
    "mitre-attack:T1497.001": "System Checks",
    "mitre-attack:T1497.002": "User Activity Based Checks",
    "mitre-attack:T1497.003": "Time Based Evasion",
    "mitre-attack:T1498": "Network DoS",
    "mitre-attack:T1498.001": "Direct Network Flood",
    "mitre-attack:T1498.002": "Reflected Network Flood",
    "mitre-attack:T1499": "Endpoint DoS",
    "mitre-attack:T1499.001": "OS Exhaustion",
    "mitre-attack:T1499.002": "Service Exhaustion",
    "mitre-attack:T1499.003": "Application Exhaustion",
    "mitre-attack:T1499.004": "Resource Starvation",
    "mitre-attack:T1500": "Compromise Hosted Software",
    "mitre-attack:T1501": "SQL Stored Procedures",
    "mitre-attack:T1502": "Parent PID Spoofing",
    "mitre-attack:T1503": "Credentials from Password Store",
    "mitre-attack:T1504": "PowerShell Profile",
    "mitre-attack:T1505": "Server Software Component",
    "mitre-attack:T1505.001": "SQL Stored Procedures",
    "mitre-attack:T1505.002": "Transport Agent",
    "mitre-attack:T1505.003": "Web Shell",
    "mitre-attack:T1505.004": "IIS Components",
    "mitre-attack:T1505.005": "Terminal Services DLL",
    "mitre-attack:T1506": "Web Session Cookie",
    "mitre-attack:T1507": "Credit Card Data from Browser",
    "mitre-attack:T1508": "Clipboard Modification",
    "mitre-attack:T1509": "Steganography",
    "mitre-attack:T1510": "Security Software Discovery",
    "mitre-attack:T1511": "Security Software Discovery",
    "mitre-attack:T1512": "Self Signed Certificate",
    "mitre-attack:T1513": "SMS 2FA Bypass",
    "mitre-attack:T1514": "Smishing (SMS Phishing)",
    "mitre-attack:T1515": "OS Install Time Discovery",
    "mitre-attack:T1516": "Query via WMI",
    "mitre-attack:T1517": "System Owner/User Discovery",
    "mitre-attack:T1518": "Software Discovery",
    "mitre-attack:T1518.001": "Security Software Discovery",
    "mitre-attack:T1519": "System Location Discovery",
    "mitre-attack:T1520": "Automated Exfiltration",
    "mitre-attack:T1521": "Encrypted Channel",
    "mitre-attack:T1522": "Symmetric Key on Device",
    "mitre-attack:T1523": "Obfuscated Command Line",
    "mitre-attack:T1524": "Parent PID Spoofing",
    "mitre-attack:T1525": "Impersonation",
    "mitre-attack:T1526": "Cloud Service Discovery",
    "mitre-attack:T1527": "Application Access Token",
    "mitre-attack:T1528": "Steal Application Access Token",
    "mitre-attack:T1529": "System Shutdown/Reboot",
    "mitre-attack:T1530": "Data from Cloud Storage Object",
    "mitre-attack:T1531": "Account Access Removal",
    "mitre-attack:T1532": "Cloud Service Dashboard",
    "mitre-attack:T1533": "Data from Cloud Storage",
    "mitre-attack:T1534": "Internal Spearphishing",
    "mitre-attack:T1535": "Unused/Unsupported Cloud Regions",
    "mitre-attack:T1536": "Compromise Infrastructure",
    "mitre-attack:T1537": "Transfer Data to Cloud Account",
    "mitre-attack:T1538": "Cloud Service Discovery",
    "mitre-attack:T1539": "Steal Web Session Cookie",
    "mitre-attack:T1540": "Cloud Instance Metadata API",
    "mitre-attack:T1541": "Cloud API Key",
    "mitre-attack:T1542": "Pre-OS Boot",
    "mitre-attack:T1542.001": "System Firmware",
    "mitre-attack:T1542.002": "Component Firmware",
    "mitre-attack:T1542.003": "Bootkit",
    "mitre-attack:T1542.004": "ROMMONkit",
    "mitre-attack:T1542.005": "TFTP Boot",
    "mitre-attack:T1543": "Create or Modify System Process",
    "mitre-attack:T1543.001": "Launch Agent",
    "mitre-attack:T1543.002": "Systemd Service",
    "mitre-attack:T1543.003": "Windows Service",
    "mitre-attack:T1543.004": "Launch Daemon",
    "mitre-attack:T1544": "Cloud Instance Metadata API",
    "mitre-attack:T1545": "Cloud Service Dashboard",
    "mitre-attack:T1546": "Event Triggered Execution",
    "mitre-attack:T1546.001": "Change Default File Association",
    "mitre-attack:T1546.002": "Screensaver",
    "mitre-attack:T1546.003": "Windows Management Instrumentation",
    "mitre-attack:T1546.004": "Unix Shell Configuration Modification",
    "mitre-attack:T1546.005": "Trap",
    "mitre-attack:T1546.006": "LC_LOAD_DYLIB Addition",
    "mitre-attack:T1546.007": "Netsh Helper DLL",
    "mitre-attack:T1546.008": "Accessibility Features",
    "mitre-attack:T1546.009": "AppCert DLLs",
    "mitre-attack:T1546.010": "AppInit DLLs",
    "mitre-attack:T1546.011": "Application Shimming",
    "mitre-attack:T1546.012": "Image File Execution Options Injection",
    "mitre-attack:T1546.013": "PowerShell Profile",
    "mitre-attack:T1546.014": "Emond",
    "mitre-attack:T1546.015": "Component Object Model Hijacking",
    "mitre-attack:T1546.016": "Installer/Setup Files",
    "mitre-attack:T1547": "Boot or Logon Autostart Execution",
    "mitre-attack:T1547.001": "Registry Run Keys / Startup Folder",
    "mitre-attack:T1547.002": "Authentication Package",
    "mitre-attack:T1547.003": "Time Providers",
    "mitre-attack:T1547.004": "Winlogon Helper DLL",
    "mitre-attack:T1547.005": "Security Support Provider",
    "mitre-attack:T1547.006": "Kernel Modules and Extensions",
    "mitre-attack:T1547.007": "Re-opened Applications",
    "mitre-attack:T1547.008": "LSASS Driver",
    "mitre-attack:T1547.009": "Shortcut Modification",
    "mitre-attack:T1547.010": "Port Monitors",
    "mitre-attack:T1547.011": "Plist Modification",
    "mitre-attack:T1547.012": "Print Processors",
    "mitre-attack:T1547.013": "Startup Items",
    "mitre-attack:T1547.014": "Active Setup",
    "mitre-attack:T1547.015": "Login Hook",
    "mitre-attack:T1548": "Abuse Elevation Control Mechanism",
    "mitre-attack:T1548.001": "Setuid/Setgid",
    "mitre-attack:T1548.002": "Bypass User Account Control",
    "mitre-attack:T1548.003": "Sudo/Sudo Caching",
    "mitre-attack:T1548.004": "Bypass Cloud API Restrictions",
    "mitre-attack:T1548.005": "Bypass macOS Gatekeeper",
    "mitre-attack:T1549": "Tool Transfer",
    "mitre-attack:T1550": "Use Alternate Authentication Material",
    "mitre-attack:T1550.001": "Application Access Token",
    "mitre-attack:T1550.002": "Pass-the-Hash",
    "mitre-attack:T1550.003": "Pass-the-Ticket",
    "mitre-attack:T1550.004": "Web Session Cookie",
    "mitre-attack:T1552": "Unsecured Credentials",
    "mitre-attack:T1552.001": "Credentials in Files",
    "mitre-attack:T1552.002": "Credentials in Registry",
    "mitre-attack:T1552.003": "Bash History",
    "mitre-attack:T1552.004": "Private Keys",
    "mitre-attack:T1552.005": "Cloud Instance Metadata API",
    "mitre-attack:T1552.006": "Group Policy Preferences",
    "mitre-attack:T1552.007": "Container API",
    "mitre-attack:T1553": "Subvert Trust Controls",
    "mitre-attack:T1553.001": "Code Signing",
    "mitre-attack:T1553.002": "Code Signing Policy Modification",
    "mitre-attack:T1553.003": "SIP and Trust Provider Hijacking",
    "mitre-attack:T1553.004": "Install Root Certificate",
    "mitre-attack:T1553.005": "Mark-of-the-Web Bypass",
    "mitre-attack:T1554": "Compromise Client Software",
    "mitre-attack:T1555": "Credentials from Password Stores",
    "mitre-attack:T1555.001": "Keychain",
    "mitre-attack:T1555.002": "Securityd Memory",
    "mitre-attack:T1555.003": "Credentials from Web Browsers",
    "mitre-attack:T1555.004": "Windows Credential Manager",
    "mitre-attack:T1555.005": "Password Managers",
    "mitre-attack:T1556": "Modify Authentication Process",
    "mitre-attack:T1556.001": "Domain Controller Authentication",
    "mitre-attack:T1556.002": "Password Filter DLL",
    "mitre-attack:T1556.003": "Pluggable Authentication Modules",
    "mitre-attack:T1556.004": "Network Device Authentication",
    "mitre-attack:T1556.005": "Replay Attacks",
    "mitre-attack:T1556.006": "Multi-Factor Authentication",
    "mitre-attack:T1557": "Adversary-in-the-Middle",
    "mitre-attack:T1557.001": "LLMNR/NBT-NS Poisoning",
    "mitre-attack:T1557.002": "ARP Cache Poisoning",
    "mitre-attack:T1557.003": "DHCP Spoofing",
    "mitre-attack:T1558": "Steal or Forge Kerberos Tickets",
    "mitre-attack:T1558.001": "Golden Ticket",
    "mitre-attack:T1558.002": "Silver Ticket",
    "mitre-attack:T1558.003": "Kerberoasting",
    "mitre-attack:T1558.004": "AS-REP Roasting",
    "mitre-attack:T1559": "Inter-Process Communication",
    "mitre-attack:T1559.001": "Component Object Model",
    "mitre-attack:T1559.002": "Dynamic Data Exchange",
    "mitre-attack:T1559.003": "XPC Services",
    "mitre-attack:T1559.004": "Apple Events",
    "mitre-attack:T1560": "Archive Collected Data",
    "mitre-attack:T1560.001": "Archive via Utility",
    "mitre-attack:T1560.002": "Archive via Library",
    "mitre-attack:T1560.003": "Archive via Custom Method",
    "mitre-attack:T1561": "Disk Wipe",
    "mitre-attack:T1561.001": "Disk Content Wipe",
    "mitre-attack:T1561.002": "Disk Structure Wipe",
    "mitre-attack:T1562": "Impair Defenses",
    "mitre-attack:T1562.001": "Disable or Modify Tools",
    "mitre-attack:T1562.002": "Disable Windows Event Logging",
    "mitre-attack:T1562.003": "Disable or Modify System Firewall",
    "mitre-attack:T1562.004": "Disable or Modify Anti-virus",
    "mitre-attack:T1562.006": "Indicator Blocking",
    "mitre-attack:T1562.007": "Disable or Modify Cloud Logs",
    "mitre-attack:T1562.008": "Disable or Modify Cloud Monitoring",
    "mitre-attack:T1562.009": "Safe Mode",
    "mitre-attack:T1562.010": "Disable or Modify System Restore",
    "mitre-attack:T1563": "Remote Service Session Hijacking",
    "mitre-attack:T1563.001": "SSH Hijacking",
    "mitre-attack:T1563.002": "RDP Hijacking",
    "mitre-attack:T1564": "Hide Artifacts",
    "mitre-attack:T1564.001": "Hidden Files and Directories",
    "mitre-attack:T1564.002": "Hidden Users",
    "mitre-attack:T1564.003": "Hidden Window",
    "mitre-attack:T1564.004": "NTFS File Attributes",
    "mitre-attack:T1564.005": "Hidden File System",
    "mitre-attack:T1564.006": "Run Virtual Instance",
    "mitre-attack:T1564.007": "VBA Stomping",
    "mitre-attack:T1564.008": "Email Hiding Rules",
    "mitre-attack:T1564.009": "Resource Forking",
    "mitre-attack:T1564.010": "Process Argument Spoofing",
    "mitre-attack:T1565": "Data Manipulation",
    "mitre-attack:T1565.001": "Stored Data Manipulation",
    "mitre-attack:T1565.002": "Transmitted Data Manipulation",
    "mitre-attack:T1565.003": "Runtime Data Manipulation",
    "mitre-attack:T1566": "Phishing",
    "mitre-attack:T1566.001": "Spearphishing Attachment",
    "mitre-attack:T1566.002": "Spearphishing Link",
    "mitre-attack:T1566.003": "Spearphishing via Service",
    "mitre-attack:T1567": "Exfiltration Over Web Service",
    "mitre-attack:T1567.001": "Exfiltration to Code Repository",
    "mitre-attack:T1567.002": "Exfiltration to Cloud Storage",
    "mitre-attack:T1567.003": "Exfiltration to Text Storage Sites",
    "mitre-attack:T1568": "Dynamic Resolution",
    "mitre-attack:T1568.001": "Fast Flux DNS",
    "mitre-attack:T1568.002": "Domain Generation Algorithms",
    "mitre-attack:T1568.003": "DNS Calculation",
    "mitre-attack:T1569": "System Services",
    "mitre-attack:T1569.001": "Launchctl",
    "mitre-attack:T1569.002": "Service Execution",
    "mitre-attack:T1570": "Lateral Tool Transfer",
    "mitre-attack:T1571": "Non-Standard Port",
    "mitre-attack:T1572": "Protocol Tunneling",
    "mitre-attack:T1573": "Encrypted Channel",
    "mitre-attack:T1573.001": "Symmetric Cryptography",
    "mitre-attack:T1573.002": "Asymmetric Cryptography",
    "mitre-attack:T1574": "Hijack Execution Flow",
    "mitre-attack:T1574.001": "DLL Search Order Hijacking",
    "mitre-attack:T1574.002": "DLL Side-Loading",
    "mitre-attack:T1574.004": "Dylib Hijacking",
    "mitre-attack:T1574.005": "Executable Installer Permissions",
    "mitre-attack:T1574.006": "Dynamic Linker Hijacking",
    "mitre-attack:T1574.007": "Path Interception by PATH Environment",
    "mitre-attack:T1574.008": "Path Interception by Search Order Hijacking",
    "mitre-attack:T1574.009": "Path Interception by Unquoted Path",
    "mitre-attack:T1574.010": "Services File Permissions Weakness",
    "mitre-attack:T1574.011": "Services Registry Permissions Weakness",
    "mitre-attack:T1574.012": "COR_PROFILER",
    "mitre-attack:T1574.013": "KernelCallbackTable",
    "mitre-attack:T1574.014": "AppDomainManager",
    "mitre-attack:T1575": "Native API Hooking",
    "mitre-attack:T1576": "Virtual Private Server",
    "mitre-attack:T1577": "Compromise User Device",
    "mitre-attack:T1578": "Modify Cloud Compute Infrastructure",
    "mitre-attack:T1578.001": "Create Cloud Instance",
    "mitre-attack:T1578.002": "Create Cloud Snapshot",
    "mitre-attack:T1578.003": "Delete Cloud Instance",
    "mitre-attack:T1578.004": "Revert Cloud Snapshot",
    "mitre-attack:T1579": "Scheduled Task/Job: Cloud",
    "mitre-attack:T1580": "Cloud Infrastructure Discovery",
    "mitre-attack:T1581": "Cloud Storage Object Access",
    "mitre-attack:T1582": "Cloud Service Enumeration",
    "mitre-attack:T1583": "Acquire Infrastructure",
    "mitre-attack:T1583.001": "Domains",
    "mitre-attack:T1583.002": "DNS Server",
    "mitre-attack:T1583.003": "Virtual Private Server",
    "mitre-attack:T1583.004": "Server",
    "mitre-attack:T1583.005": "Botnet",
    "mitre-attack:T1583.006": "Web Services",
    "mitre-attack:T1583.007": "Code Signing Certificates",
    "mitre-attack:T1584": "Compromise Infrastructure",
    "mitre-attack:T1584.001": "Domains",
    "mitre-attack:T1584.002": "DNS Server",
    "mitre-attack:T1584.003": "Virtual Private Server",
    "mitre-attack:T1584.004": "Server",
    "mitre-attack:T1584.005": "Botnet",
    "mitre-attack:T1584.006": "Web Services",
    "mitre-attack:T1585": "Establish Accounts",
    "mitre-attack:T1585.001": "Social Media Accounts",
    "mitre-attack:T1585.002": "Email Accounts",
    "mitre-attack:T1585.003": "Cloud Accounts",
    "mitre-attack:T1586": "Compromise Accounts",
    "mitre-attack:T1586.001": "Social Media Accounts",
    "mitre-attack:T1586.002": "Email Accounts",
    "mitre-attack:T1586.003": "Cloud Accounts",
    "mitre-attack:T1587": "Develop Capabilities",
    "mitre-attack:T1587.001": "Malware",
    "mitre-attack:T1587.002": "Code Signing Certificates",
    "mitre-attack:T1587.003": "Digital Certificates",
    "mitre-attack:T1587.004": "Exploits",
    "mitre-attack:T1588": "Obtain Capabilities",
    "mitre-attack:T1588.001": "Malware",
    "mitre-attack:T1588.002": "Tool",
    "mitre-attack:T1588.003": "Code Signing Certificates",
    "mitre-attack:T1588.004": "Digital Certificates",
    "mitre-attack:T1588.005": "Exploits",
    "mitre-attack:T1588.006": "Vulnerabilities",
    "mitre-attack:T1589": "Gather Victim Identity Info",
    "mitre-attack:T1589.001": "Credentials",
    "mitre-attack:T1589.002": "Email Addresses",
    "mitre-attack:T1589.003": "Employee Names",
    "mitre-attack:T1590": "Gather Victim Network Info",
    "mitre-attack:T1590.001": "Domain Properties",
    "mitre-attack:T1590.002": "DNS",
    "mitre-attack:T1590.003": "Network Trust Dependencies",
    "mitre-attack:T1590.004": "Network Topology",
    "mitre-attack:T1590.005": "IP Addresses",
    "mitre-attack:T1590.006": "Network Security Appliances",
    "mitre-attack:T1591": "Gather Victim Org Info",
    "mitre-attack:T1591.001": "Determine Physical Locations",
    "mitre-attack:T1591.002": "Business Relationships",
    "mitre-attack:T1591.003": "Identify Business Tempo",
    "mitre-attack:T1591.004": "Identify Roles",
    "mitre-attack:T1592": "Gather Victim Host Info",
    "mitre-attack:T1592.001": "Hardware",
    "mitre-attack:T1592.002": "Software",
    "mitre-attack:T1592.003": "Firmware",
    "mitre-attack:T1592.004": "Client Configurations",
    "mitre-attack:T1593": "Gather Victim Identity Info",
    "mitre-attack:T1593.001": "Social Media",
    "mitre-attack:T1593.002": "Search Engines",
    "mitre-attack:T1593.003": "Code Repositories",
    "mitre-attack:T1594": "Search Victim-Owned Websites",
    "mitre-attack:T1595": "Active Scanning",
    "mitre-attack:T1595.001": "Port/Service Scan",
    "mitre-attack:T1595.002": "Vulnerability Scanning",
    "mitre-attack:T1595.003": "Wordlist Scanning",
    "mitre-attack:T1596": "Search Open Technical Databases",
    "mitre-attack:T1596.001": "DNS/Passive DNS",
    "mitre-attack:T1596.002": "WHOIS",
    "mitre-attack:T1596.003": "Digital Certificates",
    "mitre-attack:T1596.004": "CDNs",
    "mitre-attack:T1596.005": "Scan Databases",
    "mitre-attack:T1597": "Search Closed Sources",
    "mitre-attack:T1597.001": "Threat Intel Vendors",
    "mitre-attack:T1597.002": "Purchase Technical Data",
    "mitre-attack:T1598": "Phishing for Information",
    "mitre-attack:T1598.001": "Spearphishing Service",
    "mitre-attack:T1598.002": "Spearphishing Attachment",
    "mitre-attack:T1598.003": "Spearphishing Link",
}  # fmt: skip
MITRE_ATTACK = {k: (v, "attack") for k, v in _MITRE_ATTACK.items()}

_D3FEND = {
    "d3fend:D3-ADA": "Application Directory Access",
    "d3fend:D3-AHR": "Application Hardening and Resiliency",
    "d3fend:D3-AM": "Authorization Monitoring",
    "d3fend:D3-BA": "Behavioral Analysis",
    "d3fend:D3-BR": "Bastioned Routing",
    "d3fend:D3-CC": "Cellular Connectivity Checking",
    "d3fend:D3-CDC": "Command and Control (C2) Channel Detection",
    "d3fend:D3-CIS": "Credential in Use Scoping",
    "d3fend:D3-CM": "Credential Management",
    "d3fend:D3-CP": "Connection Prefiling",
    "d3fend:D3-CPDA": "Credential Protection and Distribution Analysis",
    "d3fend:D3-CR": "Cache Verification",
    "d3fend:D3-CS": "Credential Scoping",
    "d3fend:D3-DA": "Decoy Assets (Honeypot / Honeytoken)",
    "d3fend:D3-DAAC": "Data at Rest Analysis and Control",
    "d3fend:D3-DAC": "Discretionary Access Control",
    "d3fend:D3-DB": "Dynamic Behavior Analysis",
    "d3fend:D3-DC": "Domain-based Credential Scoping",
    "d3fend:D3-DCA": "Dynamic Code Analysis",
    "d3fend:D3-DCSP": "Dynamic Containment and Sandboxing Policy",
    "d3fend:D3-DET": "Detection",
    "d3fend:D3-DH": "Dynamic Host Analysis",
    "d3fend:D3-DI": "Digital Integrity",
    "d3fend:D3-DID": "Directory Indexing Deflection",
    "d3fend:D3-DL": "Decoy Layer",
    "d3fend:D3-DM": "Decoy Messaging",
    "d3fend:D3-DNW": "Decoy Network",
    "d3fend:D3-DO": "Decoy Object",
    "d3fend:D3-DP": "DNS Policy Enforcement",
    "d3fend:D3-DR": "Dynamic Resource Allocation",
    "d3fend:D3-DS": "Decoy Space (Filespace)",
    "d3fend:D3-DSA": "Dynamic Service Analysis",
    "d3fend:D3-DU": "Deception using Decoy User",
    "d3fend:D3-DUO": "Dynamic User Ownership",
    "d3fend:D3-EC": "End-to-End Encryption Checking",
    "d3fend:D3-ED": "Event Detection",
    "d3fend:D3-EF": "Emulation for Detection",
    "d3fend:D3-EH": "Endpoint Health Checking",
    "d3fend:D3-EI": "Encryption of Information",
    "d3fend:D3-EP": "Endpoint Protection",
    "d3fend:D3-EPC": "Explicit Permissions Checking",
    "d3fend:D3-ER": "Event Reduction",
    "d3fend:D3-FA": "Fingerprinting Analysis",
    "d3fend:D3-FC": "File Carving",
    "d3fend:D3-FH": "File Hashing",
    "d3fend:D3-FI": "File Integrity",
    "d3fend:D3-FP": "File Policies",
    "d3fend:D3-FT": "File Analysis and Trust",
    "d3fend:D3-HA": "Honeypot",
    "d3fend:D3-HC": "Hardware-based Code Analysis",
    "d3fend:D3-HE": "Honeytoken",
    "d3fend:D3-HI": "Hardware Integrity",
    "d3fend:D3-HM": "Hardening and Mitigation",
    "d3fend:D3-HS": "Host Status",
    "d3fend:D3-HST": "Header and Session Token Analysis",
    "d3fend:D3-IA": "I/O Analysis",
    "d3fend:D3-IAM": "Identity and Access Management",
    "d3fend:D3-IC": "Inbound Traffic Filtering",
    "d3fend:D3-IOA": "Indicator of Attack (IoA) Detection",
    "d3fend:D3-IOC": "Indicator of Compromise (IoC) Detection",
    "d3fend:D3-IP": "Identity Provider",
    "d3fend:D3-IPC": "Inter-Process Communication Analysis",
    "d3fend:D3-ISA": "Input Validation and Sanitization Analysis",
    "d3fend:D3-ISR": "Input Size Restriction",
    "d3fend:D3-IST": "Input Saturation",
    "d3fend:D3-IV": "Input Validation",
    "d3fend:D3-KA": "Kernel Analysis",
    "d3fend:D3-LA": "Log Analysis",
    "d3fend:D3-LF": "Log Filtering",
    "d3fend:D3-MA": "Memory Analysis",
    "d3fend:D3-MAC": "Mandatory Access Control",
    "d3fend:D3-MB": "Model-based Detection",
    "d3fend:D3-MC": "Message Conversion",
    "d3fend:D3-MD": "Message Digest",
    "d3fend:D3-MF": "Message Filtering",
    "d3fend:D3-MFA": "Multi-factor Authentication",
    "d3fend:D3-ML": "Machine Learning-based Detection",
    "d3fend:D3-MM": "Media Sanitization",
    "d3fend:D3-MP": "Message Prioritization",
    "d3fend:D3-MR": "Message Rate Limiting",
    "d3fend:D3-MT": "Message Type Identification",
    "d3fend:D3-MTA": "Message Transformation and Analysis",
    "d3fend:D3-NA": "Network Analysis",
    "d3fend:D3-NAC": "Network Access Control",
    "d3fend:D3-NB": "Network Behavior Analysis",
    "d3fend:D3-NC": "Network Connectivity",
    "d3fend:D3-NF": "Network Filtering",
    "d3fend:D3-NFT": "Network Flow Analysis and Trending",
    "d3fend:D3-NIA": "Network Isolation and Access",
    "d3fend:D3-NL": "Network Layer Security",
    "d3fend:D3-NM": "Network Mapping",
    "d3fend:D3-NO": "Network Optimization",
    "d3fend:D3-NP": "Network Partitioning",
    "d3fend:D3-NR": "Network Resource Prioritization",
    "d3fend:D3-NS": "Network Segmentation",
    "d3fend:D3-NT": "Network Traffic Analysis",
    "d3fend:D3-NTP": "Network Time Protocol Verification",
    "d3fend:D3-OC": "Outbound Traffic Filtering",
    "d3fend:D3-OS": "Operating System Analysis",
    "d3fend:D3-PA": "Process Analysis",
    "d3fend:D3-PC": "Platform Certificates",
    "d3fend:D3-PCA": "Process Code Analysis",
    "d3fend:D3-PE": "Protocol Enforcement",
    "d3fend:D3-PF": "Process File Analysis",
    "d3fend:D3-PM": "Process Management",
    "d3fend:D3-PP": "Permission Policies",
    "d3fend:D3-PR": "Process Resources",
    "d3fend:D3-PS": "Process Spawning Analysis",
    "d3fend:D3-PT": "Protocol Tunneling",
    "d3fend:D3-PV": "Protocol Verification",
    "d3fend:D3-RA": "Runtime Analysis",
    "d3fend:D3-RB": "Request Batching",
    "d3fend:D3-RC": "Rate Control",
    "d3fend:D3-RD": "Request Discrepancy Analysis",
    "d3fend:D3-RE": "Reputation",
    "d3fend:D3-RL": "Resource Limiting",
    "d3fend:D3-RM": "Resource Management",
    "d3fend:D3-RP": "Request Policy Enforcement",
    "d3fend:D3-RR": "Resource Restoration",
    "d3fend:D3-RS": "Request Size Limiting",
    "d3fend:D3-SA": "Scope Analysis",
    "d3fend:D3-SAC": "Segmentation and Access Control",
    "d3fend:D3-SB": "Sandboxing",
    "d3fend:D3-SC": "Software Composition Analysis",
    "d3fend:D3-SCA": "Static Code Analysis",
    "d3fend:D3-SE": "Signature-based Detection",
    "d3fend:D3-SF": "Stateful Firewall",
    "d3fend:D3-SI": "Sensor Integration",
    "d3fend:D3-SL": "Security Logging",
    "d3fend:D3-SM": "Session Management",
    "d3fend:D3-SN": "Security Notification",
    "d3fend:D3-SO": "Secure Orchestration",
    "d3fend:D3-SP": "Secure Provisioning",
    "d3fend:D3-SR": "Session Recording",
    "d3fend:D3-SS": "Session Scoring",
    "d3fend:D3-ST": "Session Termination",
    "d3fend:D3-SVC": "Server Verification and Compliance",
    "d3fend:D3-TA": "Trust Analysis",
    "d3fend:D3-TC": "Traffic Congestion Analysis",
    "d3fend:D3-TD": "Threat Detection",
    "d3fend:D3-TI": "Threat Intelligence",
    "d3fend:D3-TL": "Threat Hunting and Intelligence",
    "d3fend:D3-TM": "Trust Modeling",
    "d3fend:D3-TN": "Trust Negotiation",
    "d3fend:D3-TP": "Traffic Policy Enforcement",
    "d3fend:D3-TR": "Threat Research",
    "d3fend:D3-TS": "Traffic Shaping",
    "d3fend:D3-TT": "Trust Transitivity",
    "d3fend:D3-UA": "User Authentication",
    "d3fend:D3-UAP": "User Account Protection",
    "d3fend:D3-UBC": "User Behavior and Credential Analysis",
    "d3fend:D3-UC": "User Consent",
    "d3fend:D3-UI": "User Interface",
    "d3fend:D3-UM": "User Management",
    "d3fend:D3-UP": "User Permission",
    "d3fend:D3-UR": "User Registration",
    "d3fend:D3-US": "User Session",
    "d3fend:D3-VA": "Vulnerability Assessment",
    "d3fend:D3-VC": "Virtualization and Containerization",
    "d3fend:D3-VI": "Vulnerability Intelligence",
    "d3fend:D3-VM": "Vulnerability Management",
    "d3fend:D3-VP": "Vulnerability Patching",
    "d3fend:D3-VS": "Vulnerability Scanning",
    "d3fend:D3-WL": "Whitelisting / Allow Listing",
    "d3fend:D3-XA": "Cross-domain Analysis",
}
D3FEND = {k: (v, "d3fend") for k, v in _D3FEND.items()}

_CAPEC = {
    "capec:1": "Accessing Functionality Not Properly Constrained by ACLs",
    "capec:2": "Inducing Account Lockout",
    "capec:3": "Using Leading 'Ghost' Character to Bypass Access Controls",
    "capec:4": "Using Alternative IP Address to Avoid Detection/Filtering",
    "capec:7": "Blind SQL Injection",
    "capec:8": "Buffer Overflow via Environment Variables",
    "capec:9": "Buffer Overflow via Local Code",
    "capec:10": "Buffer Overflow via Command Line Parameters",
    "capec:11": "Cause Web Server Misclassification",
    "capec:12": "Choosing Message Identifier",
    "capec:13": "Subverting Caching",
    "capec:14": "Client-side Injection-induced Buffer Overflow",
    "capec:15": "Command Delimiters",
    "capec:16": "Dictionary-based Password Attack",
    "capec:17": "Accessing, Modifying or Executing Executable Files",
    "capec:18": "XSS (Reflected/Stored/DOM)",
    "capec:19": "SQL Injection through SOAP Parameter Tampering",
    "capec:20": "Encryption Brute Forcing",
    "capec:21": "Exploitation of Session Variable Resources",
    "capec:22": "Exploiting Trust in Client-side Information",
    "capec:23": "File Content Injection",
    "capec:24": "Filter Failure through Multiple Extensions",
    "capec:25": "Forced Deadlock",
    "capec:26": "Leveraging Race Conditions via Symbolic Links",
    "capec:27": "HTTP Request Smuggling",
    "capec:28": "Fuzzing for Identification of Injection Vectors",
    "capec:29": "Inter-component Protocol Hijacking",
    "capec:30": "Endpoint Denial of Service",
    "capec:31": "Accessing/Intercepting/Modifying HTTP Cookies",
    "capec:32": "Pattern Matching Based Authentication Bypass",
    "capec:33": "HTTP Request Splitting",
    "capec:34": "HTTP Response Splitting",
    "capec:35": "Leverage Executable Code in Non-Executable Files",
    "capec:36": "Using Unpublished Interfaces/APIs",
    "capec:37": "Leveraging Race Conditions via Shared Resources",
    "capec:38": "Leveraging Race Conditions in Privileged Code",
    "capec:39": "Manipulating Opaque Client-based Data Tokens",
    "capec:40": "Password Recovery Exploitation",
    "capec:41": "Using Meta-characters in E-mail Header to Inject",
    "capec:42": "MIME Conversion",
    "capec:43": "Alternative Input Derivation",
    "capec:44": "Overflow Binary Resource File",
    "capec:45": "Buffer Overflow via Symbolic Links",
    "capec:46": "Overflow Variables and Tags",
    "capec:47": "Buffer Overflow via Parameter Expansion",
    "capec:48": "Passing Local Filenames to Functions Expecting URL",
    "capec:49": "Password Brute Forcing",
    "capec:50": "Password Recovery Flaw",
    "capec:51": "Poison Web Service Registry",
    "capec:52": "Embedding NULL Bytes",
    "capec:53": "Postfix, NULL Terminate, and Backslash",
    "capec:54": "Query System for Information",
    "capec:55": "Rainbow Table Password Cracking",
    "capec:56": "Session Credential Falsification through Prediction",
    "capec:57": "Session Credential Falsification through Forging",
    "capec:58": "Restful API Abuse",
    "capec:59": "Session Credential Falsification through Manipulation",
    "capec:60": "Reusing Session IDs (Session Replay)",
    "capec:61": "Session Fixation",
    "capec:62": "Cross Site Request Forgery",
    "capec:63": "Simple Script Based Content Injection",
    "capec:64": "Using Slash Encoding to Bypass Access Controls",
    "capec:65": "Sniffing Application Code",
    "capec:66": "SQL Injection",
    "capec:67": "String Format Overflow in syslog()",
    "capec:68": "Subvert Code-signing Verification",
    "capec:69": "Target Programs with Stretched Arguments",
    "capec:70": "Try Common or Default Usernames and Passwords",
    "capec:71": "Using Unicode Encoding to Bypass Validation Logic",
    "capec:72": "URL Encoding",
    "capec:73": "User-Controlled Filename",
    "capec:74": "Manipulating State",
    "capec:75": "Manipulating Writeable Terminal Devices",
    "capec:76": "Manipulating Web Input to File System Calls",
    "capec:77": "Manipulating User-Controlled Variables",
    "capec:78": "XSS Using Alternate Syntax",
    "capec:79": "Using Malicious Files",
    "capec:80": "Using UTF-8 Encoding to Bypass Validation Logic",
    "capec:81": "Web Logs Tampering",
    "capec:82": "XPath Injection",
    "capec:83": "XSS via HTTP Query Strings",
    "capec:84": "XSS via Encoded (Non-standard) Schemes",
    "capec:85": "AJAX Footprinting",
    "capec:86": "XSS via Script Injection",
    "capec:87": "XSS via Alternate XSS Vectors",
    "capec:88": "OS Command Injection",
    "capec:89": "Pharming",
    "capec:90": "Reflection Attack in Authentication Protocol",
    "capec:91": "XML Injection",
    "capec:92": "Forced Integer Overflow",
    "capec:93": "Log Injection-Tampering-Forging",
    "capec:94": "Man in the Middle Attack",
    "capec:95": "LDAP Injection",
    "capec:96": "Stack-based Buffer Overflow",
    "capec:97": "Heap-based Buffer Overflow",
    "capec:98": "Phishing",
    "capec:99": "Intent Spoofing",
    "capec:100": "Overflow Buffers",
    "capec:101": "Server Side Include Injection",
    "capec:102": "Session Sidejacking",
    "capec:103": "Clickjacking",
    "capec:104": "Cross Zone Scripting",
    "capec:105": "HTTP Request Splitting",
    "capec:106": "Integer Overflow via Overflow of Sign",
    "capec:107": "Cross-site Scripting through JSON",
    "capec:108": "Command Injection via Data/Config Files",
    "capec:109": "Object Relational Mapping Injection",
    "capec:110": "SQL Injection through SOAP Parameter Tampering",
    "capec:111": "JSON Hijacking",
    "capec:112": "Reflected XSS via CSS",
    "capec:113": "Content Spoofing",
    "capec:114": "Open Redirect",
    "capec:115": "Authentication Bypass via ...",
    "capec:116": "Rogue LDAP Server",
    "capec:117": "Parametric Injection",
    "capec:118": "Denial of Service through Resource Exhaustion",
    "capec:119": "Resource Exhaustion via ...",
    "capec:120": "Double Encoding",
    "capec:121": "XML Entity Expansion (Billion Laughs)",
    "capec:122": "Privilege Abuse",
    "capec:123": "Expired or Invalid Credentials",
    "capec:124": "Credential Theft via Social Engineering",
    "capec:125": "Credential Theft via Hardware",
    "capec:126": "Path Traversal",
    "capec:127": "Directory Indexing",
    "capec:128": "Integer Overflow via Wraparound",
    "capec:129": "Pointer Manipulation",
    "capec:130": "Excessive Allocation",
    "capec:131": "Resource Leak Exposure",
    "capec:132": "Symlink Attack",
    "capec:133": "Try All Possible Values (Brute Force)",
    "capec:134": "Email Injection",
    "capec:135": "Format String Injection",
    "capec:136": "LDAP Filter Injection via ...",
    "capec:137": "Parameter Injection",
    "capec:138": "Authentication Bypass via Session Prediction",
    "capec:139": "Relative Path Traversal",
    "capec:140": "Bypassing Validation using ...",
    "capec:141": "Cache Poisoning",
    "capec:142": "DNS Cache Poisoning",
    "capec:143": "Detect Unpublicized Web Pages",
    "capec:144": "Detect Unpublicized Services/APIs",
    "capec:145": "Checksum Spoofing",
    "capec:146": "XML External Entity (XXE) Injection",
    "capec:147": "XML Ping of the Death",
    "capec:148": "Content Spoofing via MIME Type Mismatch",
    "capec:149": "Exploit Non-standard Encoding",
    "capec:150": "Collect Data from Common/Default Locations",
    "capec:151": "Identity Spoofing",
    "capec:152": "Seed Spoofing",
    "capec:153": "Input Data Manipulation",
    "capec:154": "Resource Injection",
    "capec:155": "Screen Capture via ...",
    "capec:156": "Phishing via ...",
    "capec:157": "Sniffing Network Traffic",
    "capec:158": "Sniffing Application Code via ...",
    "capec:159": "Relay Attacks",
    "capec:160": "Exploit Test API",
    "capec:161": "Infrastructure Manipulation",
    "capec:162": "Manipulating Data/Config Files",
    "capec:163": "Hardware Component Replacement",
    "capec:164": "Mobile Application Fingerprinting",
    "capec:165": "Password Spraying",
    "capec:166": "Credential Stuffing",
    "capec:167": "Leveraging Active Directory",
    "capec:168": "Windows Admin Shares with SMB",
    "capec:169": "Footprinting",
    "capec:170": "Web Application Fingerprinting",
    "capec:171": "TCP/IP Fingerprinting",
    "capec:172": "Fingerprinting via DNS",
    "capec:173": "Fingerprinting via HTTP",
    "capec:174": "Flash Database / Service Fingerprinting",
    "capec:175": "Code/Data Injection",
    "capec:176": "Configuration/Environment Manipulation",
    "capec:177": "Create Files/Objects with Weak Permissions",
    "capec:178": "Cross-Site Scripting via ...",
    "capec:179": "Malicious File Upload",
    "capec:180": "Exploiting Incorrectly Configured Access Control",
    "capec:181": "Flash Flood",
    "capec:182": "SYN Flood",
    "capec:183": "UDP Flood",
    "capec:184": "ICMP Flood",
    "capec:185": "Ping Flood",
    "capec:186": "Malicious Data Flow",
    "capec:187": "Malicious Applets",
    "capec:188": "Reverse Engineering",
    "capec:189": "Black Box Reverse Engineering",
    "capec:190": "White Box Reverse Engineering",
    "capec:191": "Timing Attack",
    "capec:192": "Protocol Analysis",
    "capec:193": "SSL/TLS Certificate Forgery",
    "capec:194": "Fake the Source of Data (Identity Spoofing)",
    "capec:195": "Principal Spoof",
    "capec:196": "Session/Credential Hijacking",
    "capec:197": "Cross-Site Scripting via Environment Variables",
    "capec:198": "Cross-Site Scripting via ...",
    "capec:199": "XSS via ...",
    "capec:200": "Brute Force via ...",
    "capec:201": "SQL Injection via ...",
    "capec:202": "Create Malicious Client-side Code",
    "capec:203": "Manipulate Registry Information",
    "capec:204": "Leverage /Proc Filesystem",
    "capec:205": "Leverage /Dev Filesystem",
    "capec:206": "Signing Malicious Code",
    "capec:207": "Removing Important Functionality",
    "capec:208": "Replacing Trusted Executable",
    "capec:209": "XSS Using MIME Type Mismatch",
    "capec:210": "Functionality Misuse",
    "capec:211": "Exposure of Backup Files",
    "capec:212": "Functionality Bypass",
    "capec:213": "Target Influence via Search Engine Optimization",
    "capec:214": "Human CAPTCHA Bypass",
    "capec:215": "CAPTCHA Bypass via Automated Recognition",
    "capec:216": "Communication Channel Manipulation",
    "capec:217": "Exploitation of Privileges/Trust",
    "capec:218": "Spoofing of UDDI/ebXML Messages",
    "capec:219": "XML Routing Detour",
    "capec:220": "Client-Server Protocol Manipulation",
    "capec:221": "Data Serialization/Deserialization",
    "capec:222": "Unsafe Reflection",
    "capec:223": "Use of Known Domain Credentials",
    "capec:224": "Leveraging/Manipulating Configuration Files",
    "capec:225": "Anti-Debugging / Anti-Reversing Techniques",
}
CAPEC = {k: (v, "capec") for k, v in _CAPEC.items()}

ALL = {}
for m in [CWE, MITRE_ATTACK, OWASP_WEB, OWASP_AI, CAPEC, D3FEND]:
    ALL.update(m)

NAMESPACE_MAP = {
    "cwe": CWE,
    "mitre-attack": MITRE_ATTACK,
    "owasp-web": OWASP_WEB,
    "owasp-ai": OWASP_AI,
    "capec": CAPEC,
    "d3fend": D3FEND,
}

_NAMESPACE_PREFIX = {
    "cwe": "CWE",
    "mitre-attack": "MITRE ATT&CK",
    "owasp-web": "OWASP Web Top 10",
    "owasp-ai": "OWASP AI Security",
    "capec": "CAPEC",
    "d3fend": "D3FEND",
}


def resolve(tag: str) -> dict:
    """Resolve a single tag string like 'cwe:79' to its metadata."""
    for ns, items in NAMESPACE_MAP.items():
        prefix = f"{ns}:"
        if tag.startswith(prefix):
            key = tag
            if key in items:
                val = items[key]
                if isinstance(val, tuple):
                    return {"tag": tag, "title": val[0], "namespace": ns,
                            "display": _NAMESPACE_PREFIX.get(ns, ns)}
                return {"tag": tag, "title": val, "namespace": ns,
                        "display": _NAMESPACE_PREFIX.get(ns, ns)}
    return {"tag": tag, "title": tag.split(":", 1)[-1] if ":" in tag else tag,
            "namespace": "custom", "display": "Custom"}


def search(q: str, namespace: str = "") -> list:
    """Search tags by query string, optionally filtered by namespace."""
    results = []
    if namespace and namespace in NAMESPACE_MAP:
        sources = NAMESPACE_MAP[namespace]
    elif namespace:
        prefix = f"{namespace}:"
        sources = {k: v for k, v in ALL.items() if k.startswith(prefix)}
    else:
        sources = ALL
    ql = q.lower()
    for key, val in sources.items():
        name = val[0] if isinstance(val, tuple) else val
        if ql in key.lower() or ql in name.lower():
            r = resolve(key)
            results.append(r)
    return sorted(results, key=lambda x: x["tag"])[:50]
